name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get current version
      run: |
        version=$(python setup.py --version)
        echo "::set-output name=version::$version"

    - name: Build .whl and .tar.gz
      run: |
        python setup.py sdist bdist_wheel

    - name: Create source code zip and tar.gz
      run: |
        version=${{ steps.get_current_version.outputs.version }}
        git archive --format=zip --output=routexplorer-${version}.zip HEAD
        git archive --format=tar.gz --output=routexplorer-${version}.tar.gz HEAD

    - name: Push tag and release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/routexplorer-${{ steps.get_current_version.outputs.version }}.whl
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.whl
        asset_content_type: application/zip

    - name: Push tag and release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/routexplorer-${{ steps.get_current_version.outputs.version }}.tar.gz
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.tar.gz
        asset_content_type: application/gzip

    - name: Push tag and release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: routexplorer-${{ steps.get_current_version.outputs.version }}.zip
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.zip
        asset_content_type: application/zip
