name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install build dependencies
      run: |
        pip install wheel
        pip install setuptools

    - name: Get current version
      id: get_current_version
      run: |
        version=$(grep -oP "version='(\d+\.\d+\.\d+)'" setup.py | grep -oP "(\d+\.\d+\.\d+)")
        echo "::set-output name=version::$version"

    - name: Build .whl and .tar.gz
      run: |
        python setup.py bdist_wheel sdist

    - name: Create source code zip and tar.gz
      run: |
        version=${{ steps.get_current_version.outputs.version }}
        mkdir -p dist
        zip -r dist/routexplorer-${version}.zip .
        tar -czvf dist/routexplorer-${version}.tar.gz .

    - name: Push tag and release assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*.whl
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.whl
        asset_content_type: application/zip

    - name: Push tag and release assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*.tar.gz
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.tar.gz
        asset_content_type: application/gzip

    - name: Push tag and release assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*.zip
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.zip
        asset_content_type: application/zip
