name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get current version
      run: |
        version=$(python setup.py --version)
        echo "::set-output name=version::$version"

    - name: Create tag
      id: create_tag
      run: |
        git tag v${{ steps.get_current_version.outputs.version }}

    - name: Create zip file
      run: |
        version=${{ steps.get_current_version.outputs.version }}
        git archive -o routexplorer-${version}.zip HEAD

    - name: Push tag and zip file
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: routexplorer-${{ steps.get_current_version.outputs.version }}.zip
        asset_name: routexplorer-${{ steps.get_current_version.outputs.version }}.zip
        asset_content_type: application/zip

